name: TalkFree CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        run: |
          git clone https://github.com/${{ github.repository }} .
          git checkout ${{ github.ref }}

      
      # Step 5: Configure SSH for VPS
      - name: Configure SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 6: Add VPS to known hosts
      - name: Add VPS to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # Step 7: Deploy to VPS
      - name: Deploy to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PATH: /var/www/isaac/talkfree
          NGINX_SERVICE: nginx
          PHP_SERVICE: php8.1-fpm
        run: |
          echo "VPS_PATH is set to: $VPS_PATH"
          ssh -o StrictHostKeyChecking=no -o BatchMode=yes $VPS_USER@$VPS_HOST << EOF
          set -e

          # Export variables for use in the session
          export VPS_PATH="${{ env.VPS_PATH }}"
          export NGINX_SERVICE="${{ env.NGINX_SERVICE }}"
          export PHP_SERVICE="${{ env.PHP_SERVICE }}"

          # Debug: Print VPS_PATH inside the session
          echo "VPS_PATH inside SSH session: $VPS_PATH"

          # Check if VPS_PATH is set
          if [ -z "$VPS_PATH" ]; then
              echo "Error: VPS_PATH is empty"
              exit 1
          fi

          # Navigate to project directory
          echo "Navigating to $VPS_PATH"
          cd "$VPS_PATH" || { echo "Error: $VPS_PATH does not exist"; exit 1; }

          # Check if the directory is a Git repository
          if [ ! -d ".git" ]; then
              echo "Error: $VPS_PATH is not a Git repository"
              exit 1
          fi

          # Pull latest changes
          echo "Pulling latest changes..."
          git fetch --all
          git reset --hard origin/main

          # Restart services
          echo "Restarting services..."
          sudo systemctl restart "$NGINX_SERVICE"
          sudo systemctl restart "$PHP_SERVICE"

          echo "Deployment complete!"
          EOF